// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhe0g9BQexUC5HWiuF6DSr_8jJ0OL65sM',
    appId: '1:1043386161412:web:e311f8eef663e7ca815851',
    messagingSenderId: '1043386161412',
    projectId: 'campusflow-b7d36',
    authDomain: 'campusflow-b7d36.firebaseapp.com',
    storageBucket: 'campusflow-b7d36.firebasestorage.app',
    measurementId: 'G-95KL5P11J3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlmjYgBu0zohkPu_cWH69YXoKzHnGAlWY',
    appId: '1:1043386161412:android:531c4c1c251f683b815851',
    messagingSenderId: '1043386161412',
    projectId: 'campusflow-b7d36',
    storageBucket: 'campusflow-b7d36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNgThmjUzkQLU_WSEeoXM5nmO2XtS4_P8',
    appId: '1:1043386161412:ios:04d9434ef261df66815851',
    messagingSenderId: '1043386161412',
    projectId: 'campusflow-b7d36',
    storageBucket: 'campusflow-b7d36.firebasestorage.app',
    iosBundleId: 'com.example.campusflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNgThmjUzkQLU_WSEeoXM5nmO2XtS4_P8',
    appId: '1:1043386161412:ios:04d9434ef261df66815851',
    messagingSenderId: '1043386161412',
    projectId: 'campusflow-b7d36',
    storageBucket: 'campusflow-b7d36.firebasestorage.app',
    iosBundleId: 'com.example.campusflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhe0g9BQexUC5HWiuF6DSr_8jJ0OL65sM',
    appId: '1:1043386161412:web:50115b7db586a082815851',
    messagingSenderId: '1043386161412',
    projectId: 'campusflow-b7d36',
    authDomain: 'campusflow-b7d36.firebaseapp.com',
    storageBucket: 'campusflow-b7d36.firebasestorage.app',
    measurementId: 'G-BEQTPB6MFY',
  );
}
